### PR TITLE
added semanticKITTI dataset

### PR DESCRIPTION
**Pull request by tano297**
I have added SemanticKITTI [Oral at ICCV2019] to the list of datasets, as I think it can be useful for the community.

We have, in our [GitHub](https://github.com/PRBonn) and [website](http://www.ipb.uni-bonn.de/publications/) quite some repos and papers for point cloud data processing. If you are interested I can add them, but I didn't want to use your repo for personal publicity. Let me know :)

Thanks for the effort!

### CODE REVIEW

**Comment by Yochengliu** [comment]
So great! Can you add your ICCV 2019 paper link to the end? Thanks a lot.

**Comment by Yochengliu** [comment]
Now we only collect the paper and the dataset for research purpose, repos are not considered because we don't have so much time and energy, but maybe we will do this part in the future. 
I think you can add some awesome papers related to point cloud processing. 
Many Thanks :)

**Comment by tano297** [comment]
Perfect, thanks. I will add some papers then, since all of the repos correspond to a paper anyway.
I'll submit a PR soon. Again, thanks for the effor to put this repo together, it's very useful.

**Comment by tano297** [comment]
Link to iccv 2019 added :+1:

**Comment by Yochengliu** [comment]
Thanks a lot. Maybe we can meet at ICCV :)

**Pull request merged**
